### PR TITLE
added support to configure the minio config directory

### PR DESCRIPTION
**Pull request by rslllstefan**
Add the support to specify the location of your existing config.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Please resolve the conflicts @rslllstefan

**Comment by rslllstefan** [comment]
@harshavardhana I resolved the conflicts.

**Comment by harshavardhana** [comment]
Looks like there is a new conflict now @rslllstefan

**Comment by rslllstefan** [comment]
Is fixed @harshavardhana

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
